"""mig3

Revision ID: d98976775d13
Revises: 05cb9c69eb2e
Create Date: 2025-11-18 20:39:40.861365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd98976775d13'
down_revision = '05cb9c69eb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable='False',
               existing_comment='Наименование документа')
    op.alter_column('documents', 'upload_date',
               existing_type=sa.DATE(),
               nullable='False',
               existing_comment='Дата загрузки')
    op.alter_column('documents', 'upload_time',
               existing_type=postgresql.TIME(),
               nullable='False',
               existing_comment='Время загрузки')
    op.alter_column('documents', 'size',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               nullable='False',
               existing_comment='Размер файла')
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable='False',
               existing_comment='Связь с Status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Связь с Status')
    op.alter_column('documents', 'size',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               nullable=True,
               existing_comment='Размер файла')
    op.alter_column('documents', 'upload_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_comment='Время загрузки')
    op.alter_column('documents', 'upload_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='Дата загрузки')
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Наименование документа')
    # ### end Alembic commands ###
