"""initial

Revision ID: 31f4cf69c30a
Revises: 
Create Date: 2025-11-09 00:44:51.469336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f4cf69c30a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя'),
    sa.Column('surname_name', sa.String(), nullable=False, comment='Фамилия'),
    sa.Column('patronomic_name', sa.String(), nullable=False, comment='Отчество'),
    sa.Column('user_name', sa.String(), nullable=False, comment='Логин'),
    sa.Column('password', sa.String(), nullable=False, comment='Пароль'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='Пользователи'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
